# Generated by Django 4.2.1 on 2023-06-16 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sports',
            new_name='Sport',
        ),
        migrations.RenameField(
            model_name='sport',
            old_name='topic_name',
            new_name='topid_name',
        ),
    ]
