# Generated by Django 4.1.4 on 2023-06-16 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sports_sport_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cricket',
            fields=[
                ('cricketteam', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=20)),
                ('cricketteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cricket')),
            ],
        ),
        migrations.CreateModel(
            name='teamplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playername', models.IntegerField()),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='sport',
            name='topid_name',
        ),
        migrations.DeleteModel(
            name='PlayerName',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
