# Generated by Django 4.1.4 on 2023-06-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cricket_team_teamplayer_remove_sport_topid_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='playername',
            field=models.CharField(max_length=20),
        ),
    ]
