# Generated by Django 4.1.4 on 2023-06-16 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_teamplayer_playername'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='team_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cricket'),
        ),
        migrations.DeleteModel(
            name='team',
        ),
    ]
